name: moviefind
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.3
  bordered_text: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Montserrat_Bold
      fonts:
        - asset: fonts/Montserrat_Bold.ttf
    
    - family: Montserrat_Semi_Bold
      fonts:
        - asset: fonts/Montserrat_Semi_Bold.ttf

    - family: Montserrat_Regular
      fonts:
        - asset: fonts/Montserrat_Regular.ttf

    - family: Montserrat_Thin
      fonts:
        - asset: fonts/Montserrat_Thin.ttf
    
    - family: Montserrat_Light
      fonts:
        - asset: fonts/Montserrat_Light.ttf